name: CI Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get commit count
        id: commit_count
        run: echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t flask-hello-world .

      - name: Tag for local ECR 
        run: |
          docker tag flask-hello-world localhost:5000/flask-hello-world:${{ steps.commit_count.outputs.count }}
          docker tag flask-hello-world localhost:5000/flask-hello-world:latest

      - name: Tag for local ACR 
        run: |
          docker tag flask-hello-world localhost:5001/flask-hello-world:${{ steps.commit_count.outputs.count }}
          docker tag flask-hello-world localhost:5001/flask-hello-world:latest

      - name: Push to local ECR 
        run: |
          docker push localhost:5000/flask-hello-world:${{ steps.commit_count.outputs.count }}
          docker push localhost:5000/flask-hello-world:latest

      - name: Push to local ACR 
        run: |
          docker push localhost:5001/flask-hello-world:${{ steps.commit_count.outputs.count }}
          docker push localhost:5001/flask-hello-world:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: localhost:5000/flask-hello-world:${{ steps.commit_count.outputs.count }}
