name: CI Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get commit count
        id: commit_count
        run: echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          cd flask-app
          docker build -t flask-app .

      - name: Tag for local ECR 
        run: |
          docker tag flask-app localhost:5000/flask-app:${{ steps.commit_count.outputs.count }}
          docker tag flask-app localhost:5000/flask-app:latest

      - name: Tag for local ACR 
        run: |
          docker tag flask-app localhost:5001/flask-app:${{ steps.commit_count.outputs.count }}
          docker tag flask-app localhost:5001/flask-app:latest

      - name: Push to local ECR 
        run: |
          docker push localhost:5000/flask-app:${{ steps.commit_count.outputs.count }}
          docker push localhost:5000/flask-app:latest

      - name: Push to local ACR 
        run: |
          docker push localhost:5001/flask-app:${{ steps.commit_count.outputs.count }}
          docker push localhost:5001/flask-app:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: localhost:5000/flask-app:${{ steps.commit_count.outputs.count }}
